cijfer1 = int(input("voer het eerste getal in: ")) 
cijfer2 = int(input("voer het tweede getal in: ")) 
cijfer3 = int(input("voer het derde getal in: ")) 
antwoord = (cijfer1/cijfer2/cijfer3) 
afgerond = round(antwoord,4) 
print(afgerond) 